"""
services/public_url.py
----------------------
Resolve the address this deployment is actually reachable at.

WHY THIS EXISTS
---------------
Three documents carry a verification URL out of the building: the takedown
notice sent to a registrar or platform, the HTML variant of the same, and the
BSA-63 evidence certificate. Each embeds a link (and a QR code) that lets the
recipient confirm the evidence hash independently — which is the entire reason
those documents are credible.

Every one of them defaulted to `http://localhost:5000`. Behind a real
deployment that produced legal notices instructing a registrar to verify the
evidence at an address on their own machine. The document still looked
correct, which is the worst kind of wrong.

RESOLUTION ORDER
----------------
1. `PUBLIC_BASE_URL` — an explicit operator setting always wins, and is the
   only option that works for documents generated by a background job, where
   there is no request to learn the host from.
2. The current request's host, when one exists. Correct without configuration
   for anything a user triggered, and it follows the proxy headers the server
   already trusts.
3. `http://localhost:5000` — the development fallback, kept last so it is
   reached only when there is genuinely nothing better to say.
"""

from __future__ import annotations

import os

DEV_FALLBACK = "http://localhost:5000"


def public_base_url(explicit=None):
    """
    Best known public base URL, with no trailing slash.

    `explicit` is for callers that already know the answer (a request handler
    passing request.host_url); it short-circuits everything else.
    """
    if explicit:
        return str(explicit).rstrip("/")

    configured = (os.environ.get("PUBLIC_BASE_URL") or "").strip()
    if configured:
        return configured.rstrip("/")

    # Only import Flask lazily, and only use the request if one is actually
    # in scope: this module is also called from background threads and from
    # the evaluation harness, where there is no application context at all.
    try:
        from flask import has_request_context, request
        if has_request_context() and request.host_url:
            return request.host_url.rstrip("/")
    except Exception:
        pass

    return DEV_FALLBACK


def is_placeholder(url):
    """
    True when the resolved URL is the development fallback.

    Callers that put the URL in front of a third party use this to warn rather
    than silently ship an unreachable link.
    """
    return (url or "").rstrip("/") == DEV_FALLBACK
