"""
train_yolo.py
-------------
Train a custom YOLOv8 model to detect betting logos and visual patterns.

Prerequisites
-------------
1. Prepare your labelled dataset in ``datasets/`` following the structure
   described in ``datasets/README.md``.
2. Ensure ultralytics is installed: ``pip install ultralytics``
3. A ``datasets/data.yaml`` configuration file (auto-generated by this script
   if it doesn't exist).

Usage
-----
    python train_yolo.py
    python train_yolo.py --epochs 100 --batch 16 --imgsz 640 --device cpu

Trained model is saved to ``detector/saved/betting_yolo.pt``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure the project root is on sys.path
sys.path.insert(0, str(Path(__file__).parent))

from loguru import logger

# ---------------------------------------------------------------------------
# Class configuration
# ---------------------------------------------------------------------------
CLASSES = [
    "1xbet",
    "bet365",
    "parimatch",
    "stake",
    "dafabet",
    "melbet",
    "betting_slip",
    "odds_table",
    "casino_chips",
    "roulette_table",
]

DATA_YAML_TEMPLATE = """\
# YOLOv8 dataset configuration for betting detector
path: {dataset_path}
train: images/train
val: images/val

nc: {nc}
names: {names}
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def generate_data_yaml(dataset_dir: Path) -> Path:
    """Auto-generate data.yaml if it doesn't already exist."""
    yaml_path = dataset_dir / "data.yaml"
    if yaml_path.exists():
        logger.info(f"data.yaml already exists at {yaml_path}")
        return yaml_path

    content = DATA_YAML_TEMPLATE.format(
        dataset_path=str(dataset_dir.resolve()),
        nc=len(CLASSES),
        names=str(CLASSES),
    )
    yaml_path.write_text(content)
    logger.info(f"Generated {yaml_path}")
    return yaml_path


def validate_dataset(dataset_dir: Path) -> bool:
    """Check that the minimum required directories exist."""
    required = [
        dataset_dir / "images" / "train",
        dataset_dir / "images" / "val",
        dataset_dir / "labels" / "train",
        dataset_dir / "labels" / "val",
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        logger.error("Missing dataset directories:")
        for m in missing:
            logger.error(f"  {m}")
        logger.error(
            "Please follow the instructions in datasets/README.md to prepare your data."
        )
        return False
    return True


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------
def train(
    epochs: int = 50,
    batch: int = 8,
    imgsz: int = 640,
    device: str = "cpu",
    base_model: str = "yolov8n.pt",
) -> None:
    try:
        from ultralytics import YOLO  # type: ignore[import-untyped]
    except ImportError:
        logger.error("ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    dataset_dir = Path("datasets")
    if not validate_dataset(dataset_dir):
        sys.exit(1)

    yaml_path = generate_data_yaml(dataset_dir)

    # Output directory
    output_dir = Path("detector/saved")
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info(f"Loading base model: {base_model}")
    model = YOLO(base_model)

    logger.info(
        f"Starting YOLOv8 training: epochs={epochs}, batch={batch}, "
        f"imgsz={imgsz}, device={device}"
    )

    results = model.train(
        data=str(yaml_path),
        epochs=epochs,
        batch=batch,
        imgsz=imgsz,
        device=device,
        project="runs/train",
        name="betting_detector",
        exist_ok=True,
        val=True,
        save=True,
        cache=False,
    )

    # Copy best weights to detector/saved/
    best_weights = Path("runs/train/betting_detector/weights/best.pt")
    if best_weights.exists():
        import shutil
        dest = output_dir / "betting_yolo.pt"
        shutil.copy(best_weights, dest)
        logger.info(f"Best model saved to {dest}")
    else:
        logger.warning("Could not find best.pt. Check runs/train/ for results.")

    logger.info("Training complete!")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train custom YOLOv8 for betting detection")
    parser.add_argument("--epochs", type=int, default=50, help="Number of training epochs")
    parser.add_argument("--batch", type=int, default=8, help="Batch size")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size")
    parser.add_argument("--device", type=str, default="cpu", help="Device: cpu | 0 | 0,1 (GPU ids)")
    parser.add_argument("--base-model", type=str, default="yolov8n.pt", help="YOLOv8 base model variant")
    args = parser.parse_args()

    train(
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        device=args.device,
        base_model=args.base_model,
    )
